### ISSUE TITLE
منبع باز یا متن باز؟

### ISSUE THREAD

**Issue by farooghkz** [elyas8702/A-Byte-of-Python-Farsi#6]
از کدوم کلمه در ترجمه استفاده میکنید؟منبع باز یا متن یاز؟

**Comment by farooghkz** [comment]
ویکی پدیای فارسی بیشتر از متن باز استفاده کرده

**Comment by elyas8702** [comment]
راستش را بخواهید معمولا 
open source
معمولا منبع باز ترجمه می‌کنند البته بعضی جا‌ها میتوان از متن باز استفاده کرد
اگه مکانی از کتاب را درنظر دارین بگید

**Comment by elyas8702** [comment]
البته هرکدوم که بیشتر شنیده می‌شه ترجیا بهتر

**Comment by farooghkz** [comment]
خب شما خودتون کدوم رو ترجیح میدید و داخل ترجمه‌ی کتاب از کدوم استفاده میکنید؟

**Comment by elyas8702** [comment]
من بیشتر منبع باز استفاده کردم 
ولی شما که گفتید من شک کردم که از کدوم استفاده کنم یک  جستجوی کردم بهتر که متن باز استفاده بشه از این به بعد قبلی‌ها هم در اسرع وقت تحصیح می‌کنم
