### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by dddeveloperrr** [elyas8702/A-Byte-of-Python-Farsi#9]
با سلام خدمت شما
میخاستم بدونم نوشته های فارسی رو چطور در گیت ها راست چین کردید؟ من نتونستم بکنم نوشته هام چپ چین شده
با تشکر

**Comment by elyas8702** [comment]
سلام 
خیلی راحت فقط موقع مشاهده راست چین می‌شود در حالت ویرایش این امکان در حال حاضر وجود نداره. فقط کافی از تگ اچ‌ت‌م‌ل استفاده کنید .
برای راست‌چین:
<div dir=rtl>
برای چپ چین:
<div dir=ltr>

فقط کافی بالای متن فارسیتون این تگ بزارید به همین سادگی
موفق باشید

**Comment by elyas8702** [comment]
<div dir=rtl>
ببخشد حواسم نبود تگ ها را نشون نمی ده این طوری
برای پیام‌ها هم می‌توان استفاده کرد.
راست چین:
"<div dir=rtl>"
چپ چین:
"<div dir=ltr>"

**Comment by elyas8702** [comment]
(<div dir=rtl>)

**Comment by elyas8702** [comment]
‍‍‍‍`<div dir=rtl>`

**Comment by elyas8702** [comment]
<div dir=rtl>

ببخشید در حالت عادی تگ را نمایش نمی‌دهد
راستی برای پیام‌ها هم می‌توانید استفاده کنید.
برای راست چین:

`<div dir=rtl>`

برای چپ چین:

`<div dir=ltr>`

**Comment by dddeveloperrr** [comment]
سپاس از توضیحات شما
